# When a pull request is opened, updated or merged, run the lint actions.
on:
  pull_request:
    types: [ opened, synchronize, reopened, closed, edited ]
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Requirements
        run: make requirements-test

      - name: Python lint and formatting checks
        run: make check
